### Переменные
@host = http://localhost:8080
@email = kwaka88@mail.ru
@password = 123

### 1. Регистрация (просто создание в БД)
POST {{host}}/api/auth/register
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "name": "Artem Postan"
}

### 2. ОТПРАВКА КОДА (Вот здесь сработает Kafka!)
POST {{host}}/api/auth/send-code
Content-Type: application/json

{
  "email": "{{email}}"
}

### 3. Логин
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

> {% client.global.set("auth_token", response.body.token); %}

### 4. Список заметок (проверка токена)
GET {{host}}/api/notes
Authorization: Bearer {{auth_token}}

### 5. Верификация кода (введи код из письма!)
POST {{host}}/api/auth/verify-code
Content-Type: application/json

{
  "email": "kwaka88@mail.ru",
  "code": "12345"
}