spring.application.name=MyNotesNew

#spring.datasource.url=jdbc:ydb:grpcs://ydb.serverless.yandexcloud.net:2135?database=/ru-central1/b1gd88cauv7oml0bhra0/etnd24s2ffmfu78res9f&saKeyFile=${SA_KEY_PATH:src/main/resources/authorized_key.json}
spring.datasource.url=jdbc:ydb:grpcs://ydb.serverless.yandexcloud.net:2135?database=/ru-central1/b1gd88cauv7oml0bhra0/etnd24s2ffmfu78res9f&useMetadata=true
spring.datasource.driver-class-name=tech.ydb.jdbc.YdbDriver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

spring.jpa.properties.hibernate.jdbc.use_get_generated_keys=false
