spring.application.name=MyNotesNew

#spring.datasource.url=jdbc:ydb:grpcs://ydb.serverless.yandexcloud.net:2135?database=/ru-central1/b1gd88cauv7oml0bhra0/etnd24s2ffmfu78res9f&saKeyFile=${SA_KEY_PATH:src/main/resources/authorized_key.json}
spring.datasource.url=jdbc:ydb:grpcs://ydb.serverless.yandexcloud.net:2135?database=/ru-central1/b1gd88cauv7oml0bhra0/etnd24s2ffmfu78res9f&useMetadata=true
spring.datasource.driver-class-name=tech.ydb.jdbc.YdbDriver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

spring.jpa.properties.hibernate.jdbc.use_get_generated_keys=false

spring.profiles.include=local
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
spring.cloud.yandex.database.table-prefix=/local
spring.jackson.time-zone=UTC
spring.jackson.serialization.write-dates-as-timestamps=false

# spring.kafka.bootstrap-servers=localhost:9092
# spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
# spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
# spring.kafka.producer.properties.spring.json.add.type.headers=true

spring.mail.host=smtp.mail.ru
spring.mail.port=465
spring.mail.username=mynotesservice@inbox.ru
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false

spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.fallback=false